// src/main/java/com/example/chat_service/api/chat/dtos/CreatePostRequest.java

package com.example.chat_service.api.chat.dtos;

/**
 * Request DTO for creating a new post via multipart/form-data HTTP API.
 *
 * <p>This DTO maps only the <strong>text fields</strong> from a multipart request.
 * File uploads ({@code MultipartFile}) are handled directly in the controller
 * via {@code @RequestPart("image")}, not through this record.</p>
 *
 * <p><strong>Expected multipart request structure:</strong>
 * <pre>{@code
 * POST /api/posts
 * Content-Type: multipart/form-data
 *
 * --boundary
 * Content-Disposition: form-data; name="content"
 *
 * Hello world!
 * --boundary
 * Content-Disposition: form-data; name="image"; filename="cat.jpg"
 * Content-Type: image/jpeg
 *
 * [binary image data]
 * --boundary--
 * }</pre>
 * </p>
 *
 * <p><strong>Validation note:</strong> Field validation (non-null, length, etc.)
 * is enforced in the domain layer ({@code PostAggregate}), not here. This DTO is purely
 * for transport. The handler will catch domain exceptions and map to HTTP errors.</p>
 *
 * <p><strong>Why no {@code imageUrl} field?</strong> Because:
 * <ul>
 *   <li>{@code imageUrl} is generated by {@code LocalMediaStorageService} after saving the file</li>
 *   <li>The domain only needs the final path/URL string, not the upload mechanics</li>
 *   <li>Keeping HTTP concerns ({@code MultipartFile}) out of DTOs maintains clean separation</li>
 * </ul>
 * </p>
 */
public record CreatePostRequest(

        /**
         * The text content of the post.
         * <p>Validated in domain layer: non-null, non-blank, max 5000 characters.</p>
         */
        String content

) {
    // Records are immutable by design — no need for setters or builders.
    // Spring binds multipart form fields to record components by name.
}